# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4f748d9b807a73d148eca61ce1d1d5ffc1af777ef3e30055cd8dbaa20db6c1b40c7a5bd2e4c0fdf963fef3fb9294dc1917fe1a3f65f6f5c561b9ea0f7e1dded

test:
  secret_key_base: 0023664685ed71c1b7f2154fd5f65cc269fbd4af0891288e5af36d24bee17a432d0b16094ee6bf238d6b88654d62aa31cf66f490c04098f857e0e22f724b4115

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

scaleddownproduction:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
